name: flutter_opengl_example
description: Demonstrates how to use the flutter_opengl plugin.
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_opengl:
    path: ../

  cupertino_icons: ^1.0.2

  flutter_riverpod: ^2.6.1

  url_launcher: ^6.3.2

  star_menu: ^4.0.1

  file_picker: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
   - family: JetBrains
     fonts:
       - asset: assets/JetBrainsMono-Regular.ttf
