name: flutter_opengl
description: Flutter plugin to bind a Texture widget to an OpenGL ES context. Many ShaderToy shaders can be used
version: 0.10.0
homepage: https://github.com/alnitak/flutter_opengl

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

  ffi: ^2.1.3

  image: ^4.0.13

  permission_handler: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_opengl
        pluginClass: FlutterOpenglPlugin
      linux:
        pluginClass: FlutterOpenglPlugin
      macos:
        pluginClass: FlutterOpenglPlugin
      windows:
        pluginClass: FlutterOpenglPluginCApi
